# Generated by Django 5.1.7 on 2025-05-13 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('correo_institucional', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=50, unique=True)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('usuario_rol', models.CharField(choices=[('alumno', 'Alumno'), ('psicologo', 'Psicólogo'), ('moderador', 'Moderador')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Psicologo',
            fields=[
                ('id_psicologo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo_institucional', models.EmailField(max_length=254, unique=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Preferencias',
            fields=[
                ('id_preferencias', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('fecha_confirmacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialPreferencias',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cod_estudiante', models.CharField(max_length=20, unique=True)),
                ('edad', models.IntegerField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
